### ISSUE TITLE
Variables and functions

### ISSUE THREAD

**Issue by markusmoenig** [ISibboI/evalexpr#103]
Hi,

this crate is god send for me for my classical RPG creator Eldiron (www.eldiron.com).

One question. I insert my variables via eval_empty_with_context_mut(), the variables are dynamic, i.e. can be changed via the node system so I have to re-insert them every time an expression node is evaluated.

Now I have my dice throws in the expressions too, like d10, d20 (see my screenshot or the animation on Eldiron.com). I also insert them via eval_empty_with_context_mut(), i.e. a random value for each supported dice throw. However this is kind of slow and also limits the available dices, I would prefer this via a context_map, i.e. a dynamic function, but from the docs I understand these two cannot be mixed right ? I.e. dynamic variables and dynamic functions ? Somehow I probably miss something.

Thanks!

<img width="1352" alt="Screen Shot 2022-04-03 at 13 31 25" src="https://user-images.githubusercontent.com/10293923/161414963-227e7378-65cd-412f-bb62-5f5c62ebaed6.png">

**Comment by markusmoenig** [comment]
Ah, I did not think this through, even if I could set dynamic functions together with dynamic variables, the syntax would be d(10) and not d10, which is not want I want anyway.

**Comment by ISibboI** [comment]
Hi,

if you want to have a variable that "returns" a random value, e.g. dx returning a random value between 1 and x, you can implement the context trait yourself, and use `rand::thread_rng()` to generate random numbers in the `get_value()` function. E.g.:

```
impl Context for CustomContext {
    fn get_value(&self, identifier: &str) -> Option<&Value> {
        if identifier.starts_with('d') {
            let max_value: evalexpr::IntType = identifier[1..].parse();
            let mut rng = rand::thread_rng();
            // use a rand uniform distribution to generate a random number between 1 and max_value
        } else {
            // handle normal variables
        }
    }

    /* ... */
}
```

**Comment by markusmoenig** [comment]
Oh wow, thanks so much for this! Helps a lot.
