### ISSUE TITLE
Get all variables in a HashMapContext?

### ISSUE THREAD

**Issue by egel557** [ISibboI/evalexpr#108]
Is there a way to get all the variables in a HashMapContext? I need to be able to save them into a json file. There doesn't seem to be any methods for this outside of calling get_value() for each variable, which isn't possible since I don't know all of the identifiers in this scenario.

**Comment by ISibboI** [comment]
That's a very good point, I didn't think about this. This should be part of
the Context traits.

**Comment by ISibboI** [comment]
Can you check the commits I made, if it does what you need?

**Comment by egel557** [comment]
Everything looks good! It does exactly what I needed. Thanks!
