### ISSUE TITLE
Should EvalExprError implement Clone?

### ISSUE THREAD

**Issue by benwr** [ISibboI/evalexpr#121]
This is an awesome project! It's making my life a lot easier.

I'm building a tool for which it would be very useful to be able to clone an EvalExprError. Right now I'm getting around it by just converting to a string early, but passing around the errors would be much nicer. Is there a reason it doesn't implement Clone?

**Comment by ISibboI** [comment]
Are you using the latest version, or is this pull request unreleased? I can
make a new release if you need it.

**Comment by benwr** [comment]
I think the Clone instance isn't yet in the released version (8.1.0)

**Comment by ISibboI** [comment]
I now relased 8.2.0 containing the change, thank you for notifying!

**Comment by benwr** [comment]
Awesome, thanks!
