### ISSUE TITLE
Usefulness in proc macros

### ISSUE THREAD

**Issue by hecatia-elegua** [ISibboI/evalexpr#124]
I just wanted to tell you that I wanted something like this in proc macros, specifically when parsing things like array length expressions into numbers. Based on the size of the array I generate some code.
Now I solved it by going at it differently, but it might still be useful for this kind of stuff.
If I encounter that problem again I'll add an example for usage in macros.

**Comment by ISibboI** [comment]
Thank you! I'll close this for now, but if you have something more concrete, feel free to reopen.
