### ISSUE TITLE
Unexpected behaviour of the `str::from` builtin function

### ISSUE THREAD

**Issue by VianneyRousset** [ISibboI/evalexpr#169]
The `str::from` builtin function is useful to convert value to a string, however the latter has an unexpected output when a string is given as argument.

`"foo " + str::from(42)` returns `foo 42` which is fine.
`"foo " + str::from("bar")` returns `foo "bar"`, when it should be `foo bar`.

**Comment by VianneyRousset** [comment]
The `str::from` builtin function uses the `Value::to_string` implemented for the `Display` trait:

```rust
            Value::String(string) => write!(f, "\"{}\"", string),
```

The extra quotation marks above are the issue and does not follow the standard `fmt()` of a string. I guess that was a deliberate choice?

**Comment by ISibboI** [comment]
I see, thanks! Yeah, formatting a string with quotation marks was
deliberate, but adding quotation marks around a string in `str::from` was
not. I would be happy about a pull request that fixes this issue!

**Comment by VianneyRousset** [comment]
Done in #170.

Please note the choice has been made that applying `str:from` to a tuple will still add those quotation marks to contained strings.

Therefore, `str::from((42, true, "foo"))` returns `(42, true, "foo")`.

**Comment by ISibboI** [comment]
Thanks for fixing this! I'll hopefully be able to make a release during the next week.
