### ISSUE TITLE
error loading math_consts_context in v12.0.0

### ISSUE THREAD

**Issue by jeffrey182** [ISibboI/evalexpr#173]
use evalexpr::math_consts_context;

fn main() {
    let mut context = math_consts_context!().unwrap();
}

error[E0277]: the trait bound `Value<_>: From<f64>` is not satisfied
 --> src/main.rs:4:23
  |
4 |     let mut context = math_consts_context!().unwrap();
  |                       **^^^^^^^^^^^^^^^^^^^^^^ the trait `From<f64>` is not implemented for `Value<_>`, which is required by `f64: Into<_>`**

**Comment by ISibboI** [comment]
Thanks for reporting, seems like there was no test for this. I'll check it out soon, unless you want to submit a fix yourself.
