### ISSUE TITLE
Question: Way to return a `String` representing the `Node` in infix notation

### ISSUE THREAD

**Issue by MikeTheSapien** [ISibboI/evalexpr#175]
### Searched for possible leads in the source code

I searched for the code repository using [ripgrep](https://github.com/BurntSushi/ripgrep) with the following `regex` patterns: `[Ii]nfix`, `[Pp]ostfix`, `[Pp]olish`, and `[Nn]otation`, all of which, except the last one, did not return any results. The last one returned a result that lead me nowhere to my task. I'm not ruling out that this is just a skill issue (lack thereof) on my part.

I was hoping to *print* a `Node` in [Infix notation](https://en.wikipedia.org/wiki/Infix_notation).

### Other attempts to understand source code
I tried
```rust
let to_test = "\"81 + 3\"";
match ron::de::from_str::<evalexpr::Node>(&to_test) {
    Err(e) => panic!("{:#?}", e),
    Ok(d) => {
        println!("{}", d);
    }
}
```
to no avail. It did print stuff but only in *Polish notation*.

I've also searched the documentation for `Node` over [here](https://docs.rs/evalexpr/latest/evalexpr/struct.Node.html) and didn't found anything useful.

If there's no other way unless the developer would have to implement their own. No problem with that. I can also create a Pull Request if others would find use of this.

**Comment by ISibboI** [comment]
I believe that since nodes can have more than just two children, infix notation is not well defined. But feel free to argue otherwise, I am not an expert on this.

**Comment by MikeTheSapien** [comment]
First of all, thank you for your project. Most projects I've seen (even in a myriad of languages, Python, C++, TypeScript, etc) jump straight into solving or evaluating a mathematical expression. Your work rightly fits to my need in that I needed help in lexing and parsing, not the evaluation part. So big thank you for that.

---

> I am not an expert on this.
Neither am I.

---

Now on to the question.
Forgive my probable lack of grasp in your project, as I may not see what you see so that you've reached to your conclusion.

**_Only considering for now those numbers under [real numbers](https://www.cuemath.com/numbers/real-numbers/)_**, isn't it that the field of real numbers belong to a [ring](https://en.wikipedia.org/wiki/Ring_(mathematics)), and with that, they have a rule or property of [binary operation](https://en.wikipedia.org/wiki/Binary_operation), and so for each _Polish notation_ that `<evalexpr::Node as std::fmt::Display>::to_string()` generates , it has a one-to-one relationship with an _infix notation_?

For example, the infix notation `81 + 3 + 4` has a direct [one-to-one relationship](https://en.wikipedia.org/wiki/Bijection) with the Polish `+ + 81 3 4`, or `81 + (3 + 4)` maps to `+ 81  + 3 4`, and so I assume that for each Polish expression, there is an exactly one other counterpart of such expression into infix.


---

If I did not make an error in my assumptions above, do you mean that this feature isn't possible when the user inputs a `evalexpr::Operator::FunctionIdentifier` or a `evalexpr::Operator::Tuple`


---

PS. I mentioned the binary operations thing because in my understanding, any polynomial, or algebraic expression (with real numbers only), one has to _operate_ on two operands at a time with a given operator, and with that, there's a pattern to be utilized.

**Comment by ISibboI** [comment]
You can probably write a method akin to this: https://github.com/ISibboI/evalexpr/blob/main/src/tree/display.rs

**Comment by MikeTheSapien** [comment]
Yeah I would. Thanks for narrowing it down where to implement it.

I overthink-ed (don't know the past tense) my responses. I was also thinking about others who might come across this thread and wanted to have a context.

Do you think I should just work on this on my own codes? Or do you think this would add value to this project? Because if the latter is correct, I would gladly create a PR for this under your guidance (if you think so) for the proper code structure.

But my case might just be an edge case (? not sure if I used that phrase properly) and others doesn't find value in this.
