### ISSUE TITLE
Are multiple parameters for functions supported?

### ISSUE THREAD

**Issue by ISibboI** [ISibboI/evalexpr#2]

**Comment by ISibboI** [comment]
No they are not. They can be defined, but there is no way to call a function with multiple arguments as of now.

**Comment by sweihub** [comment]
Will you reopen this issue, how can we implement a custom function to accept multiple parameters?

`1 + f(a,b)`

**Comment by ISibboI** [comment]
Functions can take a tuple, that looks like multiple parameters, but
internally is just one. So the example you showed works today already, if
your function f tales a tuple of length two as parameter.

**Comment by sweihub** [comment]
OK,  I checked again your example `avg(2, 4)` that solved the issue, thanks! I left it here for later comers

Example to take multiple parameters with `evalexpr`

```rust
fn test_eval() -> anyhow::Result<(), anyhow::Error> {
    let mut context = HashMapContext::new();

    context.set_value("a".into(), 100.0.into())?;
    context.set_value("b".into(), 2.0.into())?;
    let _ = context.set_function(
        "f".into(),
        Function::new(|args| {
            let inputs = args.as_tuple()?;
            if let (Value::Float(a), Value::Float(b)) = (&inputs[0], &inputs[1]) {
                Ok(Value::Float(a + b))
            } else {
                Ok(Value::Float(0.0))
            }
        }),
    );

    let f = build_operator_tree("a * b + f(a, b)")?;
    let result = f.eval_with_context(&context)?;
    println!("result = {}", result);

    Ok(())
}
```

**Comment by ISibboI** [comment]
Great! Note that there is also `as_fixed_length_tuple(2)` (or so) that also
checks if the length of the tuple is correct.
