### ISSUE TITLE
How to access list of variables indentifier

### ISSUE THREAD

**Issue by mestachs** [ISibboI/evalexpr#37]
I'd like to port my go implementation of "equation solver" https://github.com/BLSQ/go-hesabu
to rust. Your crate looks really promising.

But one requirement to re-implement my lib it is to list variables used in an expression and deduce by a topological sort the expression by dependencies.

Is there a way to access the variable names of an expression ?
eg : "a + 10 * sin(b)" => ["a","b"]

**Comment by ISibboI** [comment]
Welcome, and thank you for the interest in my crate. I think the rust
ecosystem would benefit from a port of hesabu.

At the moment, this crate does not support listing the variable names in an
equation. But it is certainly possible to implement that feature in this
crate.

What kind of ordering do you need? The order they appear in the equation?
Or a prefix, postfix or infix order? I don't know exactly what you mean by
topological sorting, but does the way you want to order the variables fit
one of these orderings?

**Comment by mestachs** [comment]
**No special order required**. I just need a list of variables identifiers for a given expression (any order of appearance, even with duplicates is ok). 

Ideally I would like to avoid tokenizing/parsing twice as I may need to solve problems with more than [100000](https://github.com/BLSQ/go-hesabu/blob/master/test/very_large_set_of_equations.json) equations. In my go implementation, this was possible as I was using govaluate an it offer an [api](https://github.com/Knetic/govaluate#functions) where you first parse and then allow evaluation later.

**for my hesabu port** and to give you more context, the algorithm to solve the problems is as follow:

Given the following problem

```json
{
  "c": "a + 10 * b",
  "a": "10",
  "b": "10+a"
}
```

**1.** parse all equations and extract their dependencies

```json
{
  "c": ["a","b"],
  "a": [ ],
  "b": [ "a" ]
}
```

**2.** to deduce the order of evaluation of the various expressions, we do a reverse [topological sort](https://github.com/otaviokr/topological-sort#topological-sort) based on these dependencies
```json
["a", "b", "c"]
```
example implementation in [rust](https://github.com/gifnksm/topological-sort-rs/blob/master/src/lib.rs#L305)

**3.** evaluate the equations one by one and store their values in the context for further reuse

*3.1* evaluate "10" and store as "a"
```
{
  "a": "10"
}
```
*3.2* evaluate "10+a" and store as "b"
```
{
  "a": "10"
  "b": "20"
}
```
*3.3* evaluate  "a + 10 * b" and store as "c"
```
  "a": "10",
  "b": "20",
  "c": "210"
```
**4.** solution complete !

**Comment by ISibboI** [comment]
Hey mestachs,

iterating all appearing identifiers in a formula should be a really easy task. I should be able to do that soon.

I think I understand what your algorithm is doing. Do you want to use the assignment operator for your formulas? I mean do you pass formulas like `a = 5 * b` to `evalexpr`, or do you resolve the `=` yourself and then just pass the expression after the assignment, meaning `5 * b` in this case?
Because if you would pass the formula with the `=` to `evalexpr`, then there should be a way to get the identifier before the `=`, should there?

(I just started a new job and moved to a new location, so my work on this is slowed down a bit. But as soon as I get internet at home, I will be able to care for this crate properly again.)

**Comment by ISibboI** [comment]
I implemented an iterator over the identifiers of an expression.

In your use case, you would precompile an expression and then iterate over its identifiers like this:

```rust
use evalexpr;

if let Ok(tree) = build_operator_tree("a + b") {
    let mut iter = tree.iter_identifiers();
    // ...
}
```

**Comment by mestachs** [comment]
No need for assignment. Thanks a lot ! Sorry I'm on holidays. Will give it
a try next week.

**Comment by mestachs** [comment]
Is there a way to distinguish functions from variables in the identifiers ? 
eg "a + sin(b)" , the iterators returns a,b,sin

I'm learning rust, so don't really know yet what I'm doing : https://github.com/mestachs/rust-hesabu#development

**Comment by ISibboI** [comment]
This is currently not possible. But I will quickly add separate iterators for function and variable identifiers.

**Comment by ISibboI** [comment]
Now there is a method `Node::iter_variable_identifiers()` to iterate over all variable identifiers within an expression tree.

**Comment by mestachs** [comment]
Thanks a lot !
