### ISSUE TITLE
The tests fail

### ISSUE THREAD

**Issue by lovasoa** [ISibboI/evalexpr#50]
On my computer, cargo test fails.

```
$ cargo --version
cargo 1.34.0 (6789d8a0a 2019-04-01)
```

```
$ cargo test src/lib.rs
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running target/debug/deps/evalexpr-21e72120860813a4

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out

     Running target/debug/deps/integration-d0c966243a02710f

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 18 filtered out

   Doc-tests evalexpr

running 9 tests
test src/lib.rs -  (line 329) ... FAILED
test src/lib.rs -  (line 13) ... ok
test src/lib.rs -  (line 150) ... ok
test src/lib.rs -  (line 19) ... ok
test src/lib.rs -  (line 87) ... ok
test src/lib.rs -  (line 50) ... ok
test src/lib.rs -  (line 180) ... ok
test src/lib.rs -  (line 34) ... ok
test src/lib.rs -  (line 162) ... ok

failures:

---- src/lib.rs -  (line 329) stdout ----
error[E0277]: the trait bound `evalexpr::Node: serde::de::Deserialize<'_>` is not satisfied
  --> src/lib.rs:338:7
   |
12 | match ron::de::from_str::<Node>(serialized_free) {
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::de::Deserialize<'_>` is not implemented for `evalexpr::Node`
   |
   = note: required by `ron::de::from_str`

thread 'src/lib.rs -  (line 329)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:351:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    src/lib.rs -  (line 329)

test result: FAILED. 8 passed; 1 failed; 0 ignored; 0 measured; 10 filtered out

error: test failed, to rerun pass '--doc'
```

**Comment by lovasoa** [comment]
The failing test is [here](https://github.com/ISibboI/evalexpr/blob/master/src/lib.rs#L329-L344)

And indeed, it looks like `Node` does not derive Deserialize: https://github.com/ISibboI/evalexpr/blob/master/src/tree/mod.rs#L35-L39

**Comment by ISibboI** [comment]
The struct `Node` requires the `serde_support` feature flag to be enabled to implement `Deserialize`. As far as I know, there is no way to conditionally execute doctests without making the documentation ugly as of now.

For the doctests to work, you need to execute `cargo test --all-features`.

If there is a way to conditionally execute doctests based on features without altering the rendered representation of the docs, I would be happy to integrate that.

**Comment by lovasoa** [comment]
This:

```
# #[cfg(feature = "serde_support")] {
// your test here 
# }
```

should do what you want.

See https://stackoverflow.com/questions/50312190/how-can-i-conditionally-execute-a-module-level-doctest-based-on-a-feature-flag

**Comment by ISibboI** [comment]
Ah nice, I did not realize you can hide parts of the doctests like this

**Comment by ISibboI** [comment]
Well, this doesn't seem to work with current [rustdoc](https://docs.rs/crate/evalexpr/5.0.0-alpha.1) or [crates.io](https://crates.io/crates/evalexpr/5.0.0-alpha.1) or on github...

**Comment by lovasoa** [comment]
It works perfectly fine: https://docs.rs/evalexpr/5.0.0-alpha.1/evalexpr/

The problem is with your custom README generator. IMHO, you should just write your own README, and if necessary, link to the crate's documentation. The README and the documentation do not serve the same purpose, and including auto-generated files in the VCS is is confusing.

**Comment by lovasoa** [comment]
I opened an issue on their side https://github.com/phaazon/cargo-sync-readme/issues/5

**Comment by ISibboI** [comment]
Thank you for opening the issue on the `cargo-sync-readme` project.

At the moment I believe that having a synced lib.rs and readme is the simplest option.
In future, there should be three different pieces of documentation:
 * The README, which only serves as a quickstart guide and includes some links.
 * The rustdocs, that serve as your usual APIdocs without too much explanation on the expression syntax.
 * Some kind of a user guide with a good explanation of the syntax and the usage of this crate inside a project.

Then `cargo-sync-readme` won't be required anymore. But this has to wait for now.

**Comment by lovasoa** [comment]
@ISibboI cargo-sync-readme just added support for this. The new version is 0.1.3.

**Comment by ISibboI** [comment]
Thank you very much. I will incorporate this into the next release. As soon as I updated the README I will close this.

**Comment by ISibboI** [comment]
Works now. Perfect. Thank you very much for your help!
