### ISSUE TITLE
Change Context::get_function to Context::call_function

### ISSUE THREAD

**Issue by dvtomas** [ISibboI/evalexpr#73]
I'm devising my own lightweight context, and have run into the problem that `Function` is not `Send` or `Sync`. While thinking about what to do about that, I had this idea that `Function` could be removed altogether and the function 

`Context::get_function(&self, identifier: &str) -> Option<&Function>` could be changed to something like

`Context::call_function(&self, identifier: &str, value: &Value) -> EvalexprResult<Value>`

This way, `Function` could still be used as a convenience e. g. in the `HashMapContext` if practical, but the `Context` could work without the concept of an encapsulated functions at all. The whole interface would be more flexible, and perhaps could be even optimized for faster execution if necessary.

Does that sound like a plausible idea? Of course, it is a breaking change.

**Comment by ISibboI** [comment]
This is an interesting suggestion. The `call_function` method as a shortcut could definitely be added, I think that is a good idea.

However I am a bit vary about getting rid of the `Function` type in the interface. It might still be useful to someone who wants to construct a context from another by copying a function around. But on the other hand I have no idea if this `Function` type with a function pointer inside could actually be made `Send` and `Sync`, or if that is impossible. Same for `Clone`.

**Comment by dvtomas** [comment]
Context is a trait, so it can't be copied anyway, and the current Context interface doesn't provide options to enumerate available Functions, so there's no way to retrieve them and pass them to another context. 

However, it would be still possible, if someone wants to, to impl Context for some custom struct S that could e.g. contain a map of Functions, something like (off the top of my head)

```rust
struct S {
  functions: HashMap<String, Function>
}

impl Context for S {
  fn call_function(&self, identifier: &str, value: &Value) -> EvalexprResult<Value> {
    match self.functions.get(identifier) {
       Some(f) => f(value),
       None => Err(EvalExprResult::FunctionIdentifierNotFound(identifier.to_owned())),
    }
  }
}
```

This way the user can use Function if he wants to, he even has the additional liberty of accessing the HashMap of the Functions, but he is not forced to if he wants to implement `call_function` in some other way.

**Comment by ISibboI** [comment]
I see, your example is a good use case I think. Even though now it is possible to have a mismatch between `call_function` and `get_function`. However that is probably fine, a good contract would be for the `Context` implementation to describe if the functions work together soundly or not. Additionally it might be useful to have a new `Error` variant, that can be returned for functions that cannot be retrieved via `get_function`.

I will try to make the required changes to the trait soon.

**Comment by dvtomas** [comment]
I'm not sure if I made myself clear, so to avoid confusion: My idea was to remove `get_function` altogether, and have `call_function` in the `Context` only.

**Comment by dvtomas** [comment]
I had another idea in the night. What about retaining Function, probably make it require `Clone + Send + Sync + 'static` (maybe just using `fn` instead of `Box<dyn Fn>` would be fine?), and pass the available functions not to the `eval` fns, but to the `compile` fns? The `Functions` could be cloned into the eval AST itself, and during the call they would need not be looked up, they could be used directly from the Function node.

Hope this makes sense, I'm writing it in a bit of hurry

**Comment by dvtomas** [comment]
I've had a look at your commit. If you plan to eventually extend the language to support creating and modifying user defined functions, my idea from the last comment - having `Function`s inside the compiled AST - probably wouldn't work. `call_function` looks like the best way to go.

**Comment by ISibboI** [comment]
Compiling the functions into the AST would be a great idea I think.

It should not create problems with user-defined functions, as the `Function` type could just become an enum that allows either user-defined functions that themselves contain ASTs, or compiled functions, that are `fn(...) -> ...`.

I will make a separate issue for that.

**Comment by ISibboI** [comment]
I also made a separate issue for making `Function` Clone, Send and Sync, namely #76.

**Comment by dvtomas** [comment]
Amazing. I don't have anything to add right now. Thank you so much.

**Comment by ISibboI** [comment]
Perfect, I released it. Thank you so much for your input!
