### ISSUE TITLE
Bitwise operators

### ISSUE THREAD

**Issue by hanusek** [ISibboI/evalexpr#88]
Hello.
Do you plan to implement support for bitwise operators?
I need support (library) for bitwise expression.

**Comment by ISibboI** [comment]
Hi,
I think this is a very good idea. I originally did not implement them because I wanted to keep things at a higher level, but if you need them, why not. You can make a pull request, otherwise I will add them in the next days.

**Comment by ISibboI** [comment]
I have implemented some bitwise operators as builtin functions in the linked commit. You could then use them with `eval("bitxor(5, 4)")`. See also the modified integration tests in the diff of the commit for some more examples.

Is this what you need?

**Comment by hanusek** [comment]
```
#[test]
fn test_eval()
{
    use evalexpr::*;
    
    let exp = format!("bitxor(5, 4)");
    let res = eval(&exp).unwrap();
}
```
**Error:**
`thread 'tests::test_eval' panicked at 'called `Result::unwrap()` on an `Err` value: FunctionIdentifierNotFound("bitxor")', 
`

**Comment by ISibboI** [comment]
Im sorry I forgot about this. I am rather against having them as actual operators, as there will be a clash with xor and exponents. But I am curious what your application of bitwise operators with this crate would be :)

I will check out the missing function identifier.
