### ISSUE TITLE
Give access to the operator and children of a Node

### ISSUE THREAD

**Issue by kawogi** [ISibboI/evalexpr#92]
I have a use case where I want to use the crate mainly for parsing an expression in order to store the resulting tree (and maybe manipulate it).
At the moment there seems to be no way to access the operator and the children of a `Node`. I don't know if this has been a design decision but I think there's no harm in exposing those fields.

**Comment by ISibboI** [comment]
Actually, probably exposing both via methods is easiest. There are already private methods for immutable access which can just be made public, and mutable access can be added as well.

**Comment by kawogi** [comment]
One might want to add some validation (e.g. unary must have a single operand), so getter/setter seems more appropriate.

**Comment by ISibboI** [comment]
I implemented them as functions now (d2f3d415dfb0760f2f919e858cf3875b9e89e08e). However without immediate validation. The validation is done when the operator tree is evaluated. Does this work for you?

**Comment by kawogi** [comment]
Yes, that's perfect. Thanks a lot!
Code quality of this crate is on an awesome level, btw.
