### ISSUE TITLE
`123(1*2)` unexpectedly valid

### ISSUE THREAD

**Issue by dbr** [ISibboI/evalexpr#94]
I would expect `123(1*2)` to produce an error, as 123 isn't a function - however it seems to evaluate as `1*2`

Similarly `1()` evaluates to `1`, `1()()()()` also evaluates to `1`, `1()()()(9)()()` evaluates to `9`

Accepting extra pairs of parens is a bit odd but not too bad, however the former can be quite confusing, e.g in something like `a+100+(a*2)` if you accidentally omit the `+` character it'll evaluate to just `a*2`

**Comment by ISibboI** [comment]
Thank you for reporting, I will take a look.
